wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703908582.654688
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.16.1
      6: 4.29.2
      8:
      - 1
      - 5
      13: linux-x86_64
